version: "3.8"

services:
  mongodb:
    image: mongo:6
    platform: linux/amd64
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - mongoURI=mongodb://mongodb:27017/peaceful_jang
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    platform: linux/amd64 

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
